'use client'
import Menu from '@/Components/Menu'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vincenzo De Pascale',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Menu />
          {children}
        <Footer />
        </body>
    </html>
  )
}
